### ISSUE TITLE
Command RAILS_ENV=production RAILS_GROUPS=assets source $HOME/.bash_profile && bundle exec rake assets:precompile

### ISSUE THREAD

**Issue by ssotos** [stve/capistrano-local-precompile#11]
Hey, 

Thanks for this gem. I followed your instructions but I keep getting: 

Command RAILS_ENV=production RAILS_GROUPS=assets source $HOME/.bash_profile && bundle exec rake assets:precompile returned status code pid 3505 exit 127.

please advise :)

**Comment by buckstr** [comment]
If you're using ruby <= 1.9.x you're probably running into this:

https://bugs.ruby-lang.org/issues/3426

I worked around it by doing this in my deploy config

set(:precompile_cmd)   { "export RAILS_ENV=#{precompile_env.to_s.shellescape} && export #{asset_env} && #{rake} assets:precompile" }
set(:cleanexpired_cmd) { "export RAILS_ENV=#{rails_env.to_s.shellescape} && export #{asset_env} && #{rake} assets:clean_expired" }

**Comment by toymachiner62** [comment]
Recommend upgrading to Capistrano v3 and upgrading this gem to version 1.0.0 if this is still an outstanding issue.
