### ISSUE TITLE
capistrano 3

### ISSUE THREAD

**Issue by marcelamiach** [stve/capistrano-local-precompile#14]
Hello,

Any idea when the capistrano 3 version will come?

Thanks

**Comment by sheharyarn** [comment]
You could try these out in the mean time:
 - https://gist.github.com/twetzel/66de336327f79beac0e0
 - https://gist.github.com/melnikaite/3fa6850b4283865f1543

**Comment by stve** [comment]
happy to accept a pull request that supports this. I only use this on one app and it's on capistrano 2 so it's unlikely that i'll add this anytime soon.

**Comment by toymachiner62** [comment]
Support for capistrano 3 is now available.
