### ISSUE TITLE
Seems like it doesn't upload the assets after copmilation

### ISSUE THREAD

**Issue by ilyaLibin** [stve/capistrano-local-precompile#16]
My gemfile
```
group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  # gem 'spring'
  # gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'capistrano',         require: false
  gem 'capistrano-rvm',     require: false
  gem 'capistrano-rails',   require: false
  gem 'capistrano-sidekiq', require: false
  gem 'capistrano-rails-db', require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano-local-precompile', '~> 1.0.0', require: false
  gem 'capistrano-secrets-yml', require: false
  gem 'capistrano3-puma',   require: false
  gem 'capistrano-rails-console', require: false
end
```

capfile
```
# Load DSL and Setup Up Stages
require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/bundler'
require 'capistrano/rails'
require 'capistrano/secrets_yml'
require 'capistrano/local_precompile'
require 'capistrano/rvm'
require 'capistrano/puma'
require 'capistrano/sidekiq'
require 'capistrano/rails/console'
install_plugin Capistrano::Puma

# Loads custom tasks from `lib/capistrano/tasks' if you have any defined.
Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
```

deploy.rb
```
set :assets_roles, [:web, :app]

## Defaults:
set :scm,           :git
# set :branch,        :master
# set :format,        :pretty
set :log_level,     :debug
set :keep_releases, 5

## Linked Files & Directories (Default None):
# set :linked_files, %w{config/database.yml}
set :linked_dirs,  %w{log tmp/pids tmp/cache tmp/sockets vendor/bundle public/system}

namespace :puma do
  desc 'Create Directories for Puma Pids and Socket'
  task :make_dirs do
    on roles(:app) do
      execute "mkdir #{shared_path}/tmp/sockets -p"
      execute "mkdir #{shared_path}/tmp/pids -p"
    end
  end

  before :start, :make_dirs
end

namespace :deploy do
  desc "Make sure local git is in sync with remote."
  task :check_revision do
    on roles(:app) do
      unless `git rev-parse HEAD` == `git rev-parse origin/master`
        puts "WARNING: HEAD is not the same as origin/master"
        puts "Run `git push` to sync changes."
        exit
      end
    end
  end

  desc 'Initial Deploy'
  task :initial do
    on roles(:app) do
      before 'deploy:restart'
      invoke 'deploy'
    end
  end

  desc 'Restart application'
  task :start do
    on roles(:app), in: :sequence, wait: 5 do
      invoke 'puma:start'
    end
  end

  before :starting,     :check_revision
  after  :finishing,    :cleanup
  after  :finishing,    :start
  after :restart, 'sidekiq:restart'
end
```

I use rails 5, and capistrano 3.

The deploy log looks good, but in the end it doesn't takes any effects in production.

Any suggestions?

**Comment by toymachiner62** [comment]
Can you provide some debug output?

This is the task that runs an rsync to your server:

https://github.com/stve/capistrano-local-precompile/blob/master/lib/capistrano/local_precompile.rb#L47-L57

**Comment by mareczek** [comment]
I can confirm that it does not upload. It seems the original task `RBENV_ROOT=/usr/local/rbenv RBENV_VERSION=2.4.1 /usr/local/rbenv/bin/rbenv exec bundle exec rake assets:precompile` is being executed instead of the overloaded task

**Comment by toymachiner62** [comment]
What version of capistrano/local_precompile are you actually using? 1.0.0 or 1.0.1?

I'm not sure why `rake assets:precompile` is being run b/c i'm clearing the task `deploy:compile_assets` [here](https://github.com/stve/capistrano-local-precompile/blob/master/lib/capistrano/local_precompile.rb#L17) which is what calls `assets:precompile` [here](https://github.com/capistrano/rails/blob/master/lib/capistrano/tasks/assets.rake#L22-L23)

**Comment by dklanac** [comment]
@toymachiner62 I'm running into the same problem. It appears that my precompiled files don't make it up via rsync.

**Comment by eriknygren** [comment]
@dklanac @toymachiner62 @ilyaLibin @mareczek, Did anyone of you make any progress on this? I'm running into the same thing as you, also using 1.0.1, capistrano 3.7.1 and Rails 4.2.

In addition, I'm also using Webpacker which adds to the `assets:precompile` task the following way: https://github.com/rails/webpacker/blob/master/lib/tasks/webpacker/compile.rake#L26-L34

So maybe that'll cause a discrepancy. I think a lot of people (including myself) will come here from Webpacker as it got pretty rough precompiling times and rsyncing appears the be the endorsed workaround (https://github.com/rails/webpacker/issues/934). So would be lovely if we can get this working!

**Comment by dklanac** [comment]
@eriknygren I couldn't get the gem to rsync even when pulling the latest from master. I ended up writing my own to get the job done in a pinch:

`
# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

# Include tasks from other gems included in your Gemfile
require 'capistrano/rails'
require 'capistrano/rbenv'
require 'capistrano/passenger'
require 'capistrano/npm'
require 'capistrano/sidekiq'
require 'capistrano/clockwork'

# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }

namespace :load do
  task :defaults do
    set :precompile_env,   fetch(:rails_env) || 'production'
    set :assets_dir,       "public/assets"
    set :rsync_cmd,        "rsync -av --delete"

    after "bundler:install", "deploy:assets:prepare"
  end
end

# Precompile files locally for _much_ faster deployment.
namespace :deploy do
  # Clear existing task so we can replace it rather than "add" to it.
  Rake::Task["deploy:compile_assets"].clear

  namespace :assets do
    desc "Precompile the assets locally and rsync to the server"
    task :prepare do
      run_locally do
        with rails_env: fetch(:precompile_env) do
          execute "rake assets:clobber"
          execute "rm -rf node_modules && npm install"
          execute "rake assets:precompile"
          info "Sending precompiled files to the server."
          execute "#{fetch(:rsync_cmd)} ./#{fetch(:assets_dir)}/ #{fetch(:user)}@#{fetch(:server)}:#{shared_path}/#{fetch(:assets_dir)}/"
        end
      end
    end   
  end
end
`

**Comment by eriknygren** [comment]
Brilliant @dklanac, will take it for a spin!

I don't know if you're using webpacker as well, but if you do, you can replace
```
execute "rm -rf node_modules && npm install"
```
with
```
execute "rake wepbacker:clobber"
```

That's very helpful, thank you for taking the time

**Comment by toymachiner62** [comment]
@dklanac What did you change compared to this code? You could easily submit a pull request with the changes.

**Comment by dklanac** [comment]
To be honest @toymachiner62, I plowed through it as quickly as I could to get my release out the door. I recall removing some of the callbacks but can't remember the specific ones off the top of my head. I'd be happy to submit a PR although I'm not well-versed in writing tests for capistrano.

**Comment by toymachiner62** [comment]
I'd love a PR. I haven't really come up with a good way to write unit tests for capistrano.

**Comment by eriknygren** [comment]
@dklanac just one suggestion I'd make if you're making a PR. How about rsyncing into the `release_path` folder rather than overwriting it in `shared_path`. First of all, it requires less config, as we don't need to add these folders into `linked_dirs` in `deploy.rb`, and it also means that precompiled JS will be versioned so it's easier to rollback.

**Comment by amseledka** [comment]
I can't get it to work wit capistrano 3, rails 4.2 and capistrano-local-precompile (1.0.1)
any updates, please?

**Comment by nozpheratu** [comment]
Exactly what's the purpose of precompiling the assets locally, if there's no mechanism built-in to actually sync them to the server?

**Comment by toymachiner62** [comment]
Can you guys provide something to go off of? Are you getting an error of some sorts? A blank screen? The neighbor's chicken keeps barking?

**Comment by toymachiner62** [comment]
Try the new version 1.1.3 if you are still having issues.

Closing as no one is providing examples to go off of.
