### ISSUE TITLE
No `packs` directory

### ISSUE THREAD

**Issue by nkhdo** [stve/capistrano-local-precompile#17]
Hello there,

I'm trying to use your gem for my Capistrano deployment. However, I see only `assets` directory uploaded to my production server.
I'm using Webpacker so it also needs the `packs` directory. How can I fix this?

Thanks in advance!

**Comment by toymachiner62** [comment]
I'm not familiar with the Webpacker gem. Does it upload the `packs` dir without using `capistrano-local-precompile`?

**Comment by nkhdo** [comment]
No it doesn't. If I use `capistrano-local-precompile`, only `assets` directory got uploaded.

**Comment by toymachiner62** [comment]
So if it doesn't work without `capistrano-local-precompile`, it certainly won't work with it. This gem uploads whatever normally gets uploaded and nothing extra.

**Comment by nkhdo** [comment]
No, I mean if don't use `capistrano-local-precompile`, my deployment will occur normally (there are both `assets` and `packs` dir). If I use it, only 'assets' dir is uploaded
