### ISSUE TITLE
Precompiles unstaged changes

### ISSUE THREAD

**Issue by jessicard** [stve/capistrano-local-precompile#9]
When I use this to locally precompile, the precompile contains all of my unstaged changes which can cause some huge problems. I would expect it to only do the staged/committed changes.

**Comment by stve** [comment]
@jessicard looks like you found [another solution!](https://bugsnag.com/blog/replacing-the-rails-asset-pipeline-with-gulp)

I used gulp to build assets on my blog and for the past few months and I keep thinking that it could be leveraged in Rails too. I'm glad to see that you had so much success with it.

I'm thinking I may stop maintaining this gem and instead point to your blog post as the recommended approach going forward.

**Comment by jessicard** [comment]
@stve yeah! gulp has been awesome to work with, and i'm glad you're liking our solution! that sounds great (and thanks for making and maintaining gem, it was really helpful for us :) )

**Comment by toymachiner62** [comment]
Closing as there really isn't a good way to solve this other than using version control.
